language: node_js
node_js:
  - "8.11"
cache:
  yarn: true

branches:
  only:
    - master

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

script:
  - echo "no test scripts"

deploy:
  provider: script
  script: "yarn deploy"
  skip_cleanup: true
  on:
    condition: $TRAVIS_EVENT_TYPE = push
