language: node_js
node_js:
  - "8.11"
cache:
  yarn: true

if: (branch = master OR type = pull_request) AND tag IS blank

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - git diff --exit-code yarn.lock

script:
  - make publish
